schema = 3

[mod]
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.2"
    hash = "sha256-OvWCtDsVrYzM84SMQwOXPLBxnWnMC1hDm+KiI6zm3uk="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/urfave/cli-docs/v3"]
    version = "v3.1.0"
    hash = "sha256-q2eiyiyibFdT53AH72rJuyF+XLTRykPpdMc4D3Ohf/A="
  [mod."github.com/urfave/cli/v3"]
    version = "v3.6.1"
    hash = "sha256-q1WeKEvWoSyA0Wcan+Edjm71e0/vnPmqVvlfjUix7+8="
